# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiel',
            fields=[
                ('uid', models.CharField(primary_key=True, max_length=4, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('duckname', models.CharField(max_length=255)),
                ('voornaam', models.CharField(max_length=255)),
                ('tussenvoegsel', models.CharField(max_length=255)),
                ('achternaam', models.CharField(max_length=255)),
                ('voorletters', models.CharField(max_length=255)),
                ('postfix', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('woonplaats', models.CharField(max_length=255)),
                ('land', models.CharField(max_length=255)),
                ('telefoon', models.CharField(max_length=255)),
                ('mobiel', models.CharField(max_length=255)),
                ('geslacht', models.CharField(max_length=1)),
                ('voornamen', models.CharField(max_length=255)),
                ('echtgenoot', models.CharField(blank=True, max_length=4)),
                ('adresseringechtpaar', models.CharField(max_length=255)),
                ('icq', models.CharField(max_length=255)),
                ('msn', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=255)),
                ('jid', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('beroep', models.CharField(max_length=255)),
                ('studie', models.CharField(max_length=255)),
                ('patroon', models.CharField(blank=True, max_length=4)),
                ('studienr', models.IntegerField(blank=True, null=True)),
                ('studiejaar', models.IntegerField(blank=True, null=True)),
                ('lidjaar', models.IntegerField()),
                ('lidafdatum', models.DateField(blank=True, null=True)),
                ('gebdatum', models.DateField()),
                ('sterfdatum', models.DateField(blank=True, null=True)),
                ('bankrekening', models.CharField(max_length=255)),
                ('machtiging', models.IntegerField()),
                ('moot', models.CharField(max_length=1)),
                ('verticale', models.CharField(max_length=1)),
                ('verticaleleider', models.IntegerField()),
                ('kringcoach', models.CharField(blank=True, max_length=1)),
                ('o_adres', models.CharField(max_length=255)),
                ('o_postcode', models.CharField(max_length=255)),
                ('o_woonplaats', models.CharField(max_length=255)),
                ('o_land', models.CharField(max_length=255)),
                ('o_telefoon', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('kerk', models.CharField(max_length=255)),
                ('muziek', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=11)),
                ('eetwens', models.CharField(max_length=255)),
                ('corvee_punten', models.IntegerField()),
                ('corvee_punten_bonus', models.IntegerField()),
                ('ontvangtcontactueel', models.CharField(max_length=8)),
                ('kgb', models.TextField()),
                ('soccieid', models.IntegerField(db_column='soccieID')),
                ('createterm', models.CharField(db_column='createTerm', max_length=255)),
                ('socciesaldo', models.FloatField(db_column='soccieSaldo')),
                ('maalciesaldo', models.FloatField(db_column='maalcieSaldo')),
                ('changelog', models.TextField()),
                ('ovkaart', models.CharField(max_length=255)),
                ('zingen', models.CharField(max_length=255)),
                ('novitiaat', models.TextField()),
                ('lengte', models.IntegerField()),
                ('vrienden', models.TextField()),
                ('middelbareschool', models.CharField(db_column='middelbareSchool', max_length=255)),
                ('novietsoort', models.CharField(db_column='novietSoort', max_length=255)),
                ('matrixplek', models.CharField(db_column='matrixPlek', max_length=255)),
                ('startkamp', models.CharField(max_length=255)),
                ('medisch', models.TextField()),
                ('novitiaatbijz', models.TextField(db_column='novitiaatBijz')),
            ],
            options={
                'db_table': 'profielen',
            },
            bases=(models.Model,),
        ),
    ]
